name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: create needed bin folder
      run: mkdir bin

    - name: create needed build folder
      run: mkdir build

    - name: make build
      run: make all

    - name: make clean
      run: make clean
